<?php require('template/header.phtml'); ?>

<div class="container-fluid">

    <h1><strong>Please login or sign up</strong></h1>

    <div class="col-xs-12 col-sm-6 col-lg-4" id="formBackground">
        <form name="login" method="POST" action="../login.php">

            <div id="loginBox">
                <h3>Login</h3>
                <label>username:<br/>
                    <input type="text" name="username" class="form-control" required></label><br>

                <label>password:<br/>
                    <input type="password" name="password" class="form-control" required></label><br>


                <label>Prove you're human...<br/>
                    <img src="../images/antispam.gif" id="captcha">
                    <p>Please enter the text in the image</p>
                    <input type="text" name="anti-spam" class="form-control" required></label><br>


                <input type="submit" name="login" value="Login" class="btn btn-primary">
            </div>


        </form>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4" id="formBackground">
        <form name="signUp" method="POST" action="../login.php">

            <h3>Sign up</h3>

            <div class="form-group">
                <label>username:<br/>
                    <input type="text" name="username" class="form-control" required></label><br>
            </div>

            <div class="form-group">
                <label>password:<br/>
                    <input type="password" name="password" class="form-control" required></label><br>
            </div>

            <div class="form-group">

                <label>email:<br/>
                    <input type="email" name="email" class="form-control" required></label><br>
            </div>

            <label>Mobile Number (07 7777 777 77) 10 digits only:<br/>
                <input type="number" name="mobileNo" class="form-control" required></label><br>

            <label>Address:<br/>
                <input type="text" name="address" class="form-control" required></label><br>

            <label>Prove you're human...
                <img src="../images/antispam.gif" id="captcha">
                <p>Please enter the text in the image</p>
                <input type="text" name="anti-spam" class="form-control" required></label><br>


            <input type="submit" name="sign-up" value="sign-up" class="btn btn-primary">

        </form>
    </div>

</div>

<?php require('template/footer.phtml') ?>
