<?php require('template/header.phtml') ?>

<div class="container">
    <h1>Admin Page</h1>

    <p>Welcome to the admin page, here you can manage all aspects of your data</p>

    <p>*Need: search function for data, AJAX?</p>

    <form>
        <h1>Users</h1>

        <h2>Add user</h2>

        <h2>Edit user details</h2>
        <p>Search for user, then edit details</p>

        <h2>Remove user</h2>
    </form>


    <form>
        <h1>Advert</h1>

        <h2>Post Advert</h2>
        <p>...</p>

        <h2>Remove Advert</h2>
        <p>...</p>

        <h2>Set Advert Expiry date</h2>
        <p>...</p>

    </form>

    <form>
        <h1>Wish list</h1>

        <h2>Add to wish list</h2>
        <h2>Remove from wish list</h2>
    </form>



</div>
<?php require('template/footer.phtml') ?>
