<?php require('template/header.phtml') ?>

<div class="container-fluid">
<!--    <div id="boxModel" class="col-xs-10 col-md-8 col-lg-8">-->

        <div class="page-header">
            <h2>Browse</h2>
        </div>

        <div class="row">
        <div id="filter">
<!--            <aside class="float-right">-->

                <form name="filter" method="GET" action="../browse.php">

                    <div>
                        <p class="h3">Filter your search</p>
                    </div>

<!--                    <div class="form-group">-->
<!--                        <label for="carDropMake">Car make</label>-->
<!--                        <select name="carDropMake" id="carDrop">-->
<!--                            <option value="">NO SELECTION</option>-->
<!--                            <option disabled>Regular Cars</option>-->
<!--                            <option value="Mercedes"> Mercedes</option>-->
<!--                            <option value="BMW"> BMW</option>-->
<!--                            <option value="Ford"> Ford</option>-->
<!--                            <option value="Audi"> Audi</option>-->
<!---->
<!--                            <option disabled>Electric Cars</option>-->
<!--                            <option value="Tesla"> Tesla</option>-->
<!---->
<!--                            <option disabled>Super cars</option>-->
<!--                            <option value="Lambo"> Lambo</option>-->
<!--                            <option value="Ferrari"> Ferrari</option>-->
<!--                        </select>-->
<!--                    </div>-->
<!---->
<!--                    <div class="form-group">-->
<!--                        <label for="carDropPrice">Price</label>-->
<!--                        <select name="carDropPrice" id="carDropPrice">-->
<!--                            <option value="">NO SELECTION</option>-->
<!--                            <option value="1000"><1000</option>-->
<!--                            <option value="5000"><5000</option>-->
<!--                            <option value="10000"><10,000</option>-->
<!--                            <option value="20000"><20,000</option>-->
<!--                            <option value="50000"><50,000</option>-->
<!--                            <option value="100000"><100,000</option>-->
<!--                            <option value="250000"><250,000</option>-->
<!--                            <option value="500000"><500,000</option>-->
<!--                            <option value="750000"><750,000</option>-->
<!--                            <option value="1000000"><1,000,000</option>-->
<!--                        </select>-->
<!--                    </div>-->
<!---->
<!---->
<!--                    <div class="form-group">-->
<!--                        <label for="carDropColor">Color</label>-->
<!--                        <select name="carDropColor" id="carDropColor">-->
<!--                            <option value="">NO SELECTION</option>-->
<!--                            <option value="black"> Black</option>-->
<!--                            <option value="white"> White</option>-->
<!--                            <option value="grey"> Grey</option>-->
<!--                            <option value="red"> Red</option>-->
<!--                            <option value="orange"> Orange</option>-->
<!--                            <option value="blue"> Blue</option>-->
<!--                        </select>-->
<!--                    </div>-->
<!--                    <button type="submit" name="filterSubmit" value="filterSubmit" class="btn btn-success">Submit</button>-->

                        <div class="btn-group">

                            <button type="submit" name="searchAll" class="btn btn-primary">Search all adverts</button>
                            <button type="submit" name="low2high" value="low2high" class="btn btn-primary"">Filter low to high (price)</button>
                            <button type="submit" name="high2low" value="high2low" class="btn btn-primary">Filter high to low (price)</button>
                            <button type="submit" name="titleASC" value="titleASC" class="btn btn-primary">Filter title (ASC)</button>
                            <button type="submit" name="titleDESC" value="titleDESC" class="btn btn-primary">Filter title (DESC)</button>

<!--                            Free text search-->
                            <input type="text" name="search" placeholder="Search..."/>
                            <button type="submit" name="freeSearchSubmit" value="getFreeSearch" class="btn btn-success">Submit Search <span class="glyphicon glyphicon-search"></span></button>
                            <label class="control-label" for="lookUp">Find your next car</label>-->.

                            <div class="input-group">
                                <input id="lookUp" type="text" placeholder="Search..." onkeyup="results(this.value)">
                                <span class="glyphicon glyphicon-search" style="margin:5px"></span>

                                <div id="results" class="overlay"></div>
                                <script src="../js/AJAX.js"></script>
                            </div>

                           <br>

                        </div>
                </form>
<!--            </aside>-->


        </div>
        </div>



            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" id="AJAX">


                <!--        For each loop to loop through advert data so that the user can view advert information.-->

                <div class="row">
<!--                    <div class="col-xs-4">-->
                <?php foreach ($view->advertDataSet as $advertData) {

                    echo

//                        '<div class="row">'.

                        '<div class="col-xs-12 col-sm-6 col-lg-4">'.

                        '<div class = "card" id="bottom">' .


                        '<div class = "card-body" >' .


                        '<h1 class="card-title"> Name of Car: ' . $advertData->getTitle() . '</h1>' .

                        '<h2 class="card-title" > Price:</h2>' .

                        '<p class="card-text" >£' . $advertData->getPrice() . '</p>' .

                        '<img src="../images/' . $advertData->getPhotoName() . ' "  class="img-thumbnail" id="images"  alt="No Image Available." />' . '<br/>' .

                        '<h2 class="card-title" >Description: </h2>' .

                        '<p1 class="card-text" > ' . $advertData->getDescription() . '</p1>' . '<br/>' .

                        '<h2 class="card-title" >Color: </h2>' .

                        '<p1 class="card-text" >' . $advertData->getColor() . '<p1/>' . '<br/>' .

                        '<p1 class="card-text"> Advert Id: ' . $advertData->getAdvertID() . '</p1>' . '<br/>' .

                        '<p>Click add to wish list to see owner details...</p>'.

                        '<a href="../wishlist.php?id=' . $advertData->getAdvertId() . ' " type="button" class="btn btn-primary">Add to wish list</a>'

//                        '<a href="contactUs.php?id=' . $advertData->getFK_userID() . '" type="button" class="btn btn-primary">Contact Owner</a>'


//                        . '</div>'
                        . '</div>'
                        . '</div>'
                        . '</div>'
                        . '<br/>';
                }
                ?>

<!--                </div>-->
                </div>



<?php //foreach ($view->userDataSet as $userData) {
//
//'        <div class="modal fade" id="browseModal" tabindex="-1" role="dialog" aria-labelledby="browseModalLabel" aria-hidden="true">
//' .
//'            <div class="modal-dialog" role="document">
//' .
//'                <div class="modal-content">
//' .
//'                    <div class="modal-header">
//' .
//'                        <h5 class="modal-title" id="browseModalLabel">Details to contact owner</h5>
//' .
//'                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
//' .
//'                            <span aria-hidden="true">&times;</span>
//' .
//'                        </button>
//' .
//'                    </div>
//' .
//'                    <div class="modal-body">
//
//
//
//
//
//
//
//
//
//' .
//'                        <form>
//' .
//'                            <div class="form-group">
//' .
//'                                <label for="recipient-name" class="col-form-label">Username:</label>
//' .
////                        '                                <input type="text" class="form-control" name ="subject" id="subject">
////' .
//'<p>GET USER NAME</p>'.
//'                            </div>
//' .
//'                            <div class="form-group">
//' .
//'                                <label for="message-text" class="col-form-label">Email</label>
//' .
////                        '                                <textarea class="form-control" name ="enquiry" id="message-text"></textarea>
////' .
//'<p>GET Email</p>'.
//
//'                                <label for="message-text" class="col-form-label">Address</label>
//' .
//'<p>GET Address</p>'.
//'                            </div>
//' .
//'                        </form>
//
//' .
//'                    </div>
//' .
//'                    <div class="modal-footer">
//' .
//'                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
//' .
//'                        <button type="button" class="btn btn-primary" name="contactBtn"  > ' .' end message'. '</button>
//' .
//'                    </div>
//' .
//'                </div>
//' .
//'            </div>
//' .
//'        </div>
//' .
//'    </div>
//' .
//'</div>'
//. '<br/>'
?>


            </form>

    <div>
<!--        <ul class="pagination pagination-sm">.-->

<!--            <!--                        --><?php
//            // Use default styling/automatic generation
//            //                        echo $pagination->getLinksHtml("http://localhost/browse.php", "pg");
//            //
//            //                        // custom styling
//            //                        for($i=1; $i<=$pagination->getNumPages(); $i++) {
//            //                            echo 'test';
//            //                        }
//            //
//            //                        ?>
<!---->
<!---->
<!---->
<!--            <li><a href="#">1</a></li>-->
<!--            <li><a href="#">2</a></li>-->
<!--            <li><a href="#">3</a></li>-->
<!--            <li><a href="#">4</a></li>-->
<!--            <li><a href="#">5</a></li>-->
<!--        </ul>-->
<!--    </div>-->

<!--</div>-->
    </div>
</div>

                <?php require('template/footer.phtml') ?>
