<?php require('template/header.phtml') ?>

<div class="container">
    <div id="boxModel" class="col-xs-12">

        <h3>Browse</h3>

        <div id="filter">
            <aside class="float-left">

                <form name="filter" method="POST" action="browse.php">
                    <div class="form-group">
                        <label for="carDropMake">Car make</label>
                        <select id="carDrop">
                            <option value="volvo">Volvo</option>
                            <option value="saab">Saab</option>
                            <option value="mercedes">Mercedes</option>
                            <option value="audi">Audi</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="carDropPrice">Price</label>
                        <select id="carDropPrice">
                            <option value="<1000"><1000</option>
                            <option value="<5000"><5000</option>
                            <option value="<10000"><10,000</option>
                            <option value="<20000"><20,000</option>
                            <option value="<50000"><50,000</option>
                            <option value="<100000"><100,000</option>
                        </select>
                    </div>


                    <div class="form-group">
                        <label for="carDropColour">Color</label>
                        <select name="select" id="carDropColour">
                            <option value="black"> Black</option>
                            <option value="white"> White</option>
                            <option value="grey"> Grey</option>
                            <option value="red"> Red</option>
                            <option value="blue"> Blue</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </aside>
        </div>

        <button class = ""> Search all adverts </button>



<div class="pull-right">

<!--    This should be apart of a browse all method in the advert data set.
        User can select which data they would like to see.-->

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

<!--        For each loop to loop through advert data so that the user can view advert information.-->

        <?php foreach ($view->advertDataSet as $advertData) {
            echo

                '<div class = "card">'.

                '<div class = "card-body">'.



                '<h1 class="card-title"> Name of Car: ' .$advertData->getTitle().'</h1>'.

                '<h2 class="card-title"> Price:</h2>'.

                '<p class="card-text">' .$advertData->getPrice().'</p>'.

                '<img src="images/' . $advertData->getPhotoName() . ' "  class="img-thumbnail" id="images"  alt="No Image Available." />'. '<br/>'.

                '<h2 class="card-title">Description: </h2>'.

                '<p1 class="card-text"> ' .$advertData->getDescription().'</p1>'. '<br/>'.

                '<h2 class="card-title">Color: </h2>'.

                '<p1 class="card-text">' .$advertData->getColor().'<p1/>'.'<br/>'.

                '<p1 class="card-text"> Advert Id: ' .$advertData->getAdvertID().'</p1>'. '<br/>'.

//                '<p1> Posted by: ' .$userData->getUsername().'<p1/>'.'<br/>'.

                '<button type="button" class="btn btn-primary">Contact owner</button>'.

                //Contact Owner Modal

                '                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Contact Owner *MODAL*</button>
'.
                '        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
'.
                '            <div class="modal-dialog" role="document">
'.
                '                <div class="modal-content">
'.
                '                    <div class="modal-header">
'.
                '                        <h5 class="modal-title" id="exampleModalLabel">New message to owner</h5>
'.
                '                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
'.
                '                            <span aria-hidden="true">&times;</span>
'.
                '                        </button>
'.
                '                    </div>
'.
                '                    <div class="modal-body">
'.
                '                        <form>
'.
                '                            <div class="form-group">
'.
                '                                <label for="recipient-name" class="col-form-label">Recipient:</label>
'.
                '                                <input type="text" class="form-control" id="recipient-name">
'.
                '                            </div>
'.
                '                            <div class="form-group">
'.
                '                                <label for="message-text" class="col-form-label">Message:</label>
'.
                '                                <textarea class="form-control" id="message-text"></textarea>
'.
                '                            </div>
'.
                '                        </form>
'.
                '                    </div>
'.
                '                    <div class="modal-footer">
'.
                '                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
'.
                '                        <button type="button" class="btn btn-primary">Send message</button>
'.
                '                    </div>
'.
                '                </div>
'.
                '            </div>
'.
                '        </div>
'.
                '    </div>
'.
                '</div>
'.

            '<button type="button" class="btn btn-secondary">Add to wishlist</button>'

                .'<div/>'
                .'<div/>'
                .'<br/>';
        } ?>
    </form>
</div>


<!--        Implement this in to the PHP loop, it's modal form-->
<!---->
<!--        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Contact Owner *MODAL*</button>-->
<!---->
<!--        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">-->
<!--            <div class="modal-dialog" role="document">-->
<!--                <div class="modal-content">-->
<!--                    <div class="modal-header">-->
<!--                        <h5 class="modal-title" id="exampleModalLabel">New message to owner</h5>-->
<!--                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                            <span aria-hidden="true">&times;</span>-->
<!--                        </button>-->
<!--                    </div>-->
<!--                    <div class="modal-body">-->
<!--                        <form>-->
<!--                            <div class="form-group">-->
<!--                                <label for="recipient-name" class="col-form-label">Recipient:</label>-->
<!--                                <input type="text" class="form-control" id="recipient-name">-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <label for="message-text" class="col-form-label">Message:</label>-->
<!--                                <textarea class="form-control" id="message-text"></textarea>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                    <div class="modal-footer">-->
<!--                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
<!--                        <button type="button" class="btn btn-primary">Send message</button>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--    </div>-->
<!--</div>-->



<?php require('template/footer.phtml') ?>
