<?php require('template/header.phtml') ?>


<div class="container">

    <div class="page-header">
        <h3>Contact Owner</h3>
    </div>

    <p><strong>Please fill out your details.</strong></p>
    <form name="contact" method="post" action="../contactUs.php">

        <div class="container">

            <div>
                <label>Name: </label>
                <p>USER NAME HERE</p>

                <label>Email: </label>
                <p>EMAIL HERE</p>

                <label>Address: </label>
                <p>ADDRESS HERE</p>

<!--                <label>Address: </label>-->
<!--                <input type="text" name="address" required></label><br>-->
<!---->
<!--                <label>Email: </label>-->
<!--                <input type="text" name="mobNo" required><br>-->
<!---->
<!--                <label>Your enquiry: </label>-->
<!--                <input type="text" name="enquiry" required><br>-->

            </div>

<!--            <div>-->
<!--                <label>We'd love to hear from you!</label><br>-->
<!--                <textarea style="width:80% name="enquiry" required></textarea>-->
<!--            </div>-->

            <div >
                <input type="submit" name="conSubmit" value="Submit" class="btn btn-primary">
            </div>

        </div>

    </form>

</div>

<?php require('template/footer.phtml') ?>
