<?php require('template/header.phtml') ?>

<h3>Contact us</h3>

<body>
<div class="container">
    <p><strong>Please fill out your details.</strong></p>
    <form name="contact" method="post" action="#.php">

        <div class="container">

            <div>
                <label>Name</label>
                <input type="text" name="name" required></label><br>

                <label>Address:</label>
                <input type="text" name="address" required></label><br>

                <label>Mobile number</label>
                <input type="password" name="mobNo" required><br>
            </div>

            <div>
                <label>We'd love to hear from you!</label><br>
                <textarea rows="4" cols="50" required></textarea>
            </div>

            <div>
                <input type="submit" name="conSubmit" value="Submit" class="btn btn-primary">
            </div>

        </div>

    </form>

</div>
</body>

<?php require('template/footer.phtml') ?>
