<?php require('template/header.phtml') ?>

<h3>Contact us</h3>

<body>
<div class="container">
    <p><strong>Please fill out your details.</strong></p>
    <form name="contact" method="post" action="../contactUs.php">

        <div class="container">

            <div>
                <label>Name: </label>
                <input type="text" name="name" required></label><br>

<!--                <label>Address: </label>-->
<!--                <input type="text" name="address" required></label><br>-->
<!---->
<!--                <label>Email: </label>-->
<!--                <input type="text" name="mobNo" required><br>-->
<!---->
<!--                <label>Your enquiry: </label>-->
<!--                <input type="text" name="enquiry" required><br>-->

            </div>

<!--            <div>-->
<!--                <label>We'd love to hear from you!</label><br>-->
<!--                <textarea style="width:80%" required></textarea>-->
<!--            </div>-->

            <div >
                <input type="submit" name="conSubmit" value="Submit" class="btn btn-primary">
            </div>

        </div>

    </form>

</div>
</body>

<?php require('template/footer.phtml') ?>
