<?php require('template/header.phtml') ?>

<div class="container">
<!--    <div id="boxModel" class="col-xs-6">-->

<!--        <div class = "pull-left">-->

            <div class="jumbotron">

                <h1 class="display-3">Welcome!</h1>
                <p class="lead">This is a car web site where you can view & browse cars.</p>
                <hr class="my-2">
                <p>If you see anything you like, feel free to contact us</p>
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="browse.php" role="button">Go browse</a>
                </p>

            </div>

</div>

<?php require('template/footer.phtml') ?>
