<?php
//if(!(isset($_POST['login'])) && (isset($_SESSION['login_user']))){
 //   require ('template/header.phtml');
//} else {
    require ('template/header.phtml');
 //   echo 'try again';
//}
?>
<div class="container-fluid">
    <div id="boxModel" class="col-xs-12">
    <h1><strong>Please login or sign up</strong></h1>



        <form name="login" method="POST" action="../login.php">

            <div id="loginBox">
                <h3>Login</h3>
                <label>username:
                    <input type="text" name="username" required></label><br>

                <label>password:
                    <input type="password" name="password" required></label><br>


                    <label>Prove you're human...
                        <img src="/images/antispam.gif">
                        <p>Please enter the text in the image</p>
                        <input type="text" name="anti-spam" required></label><br>


                <input type="submit" name="login" value="Login" class="btn btn-primary">
            </div>


        </form>


        <form name="signUp" method="POST" action="../login.php">

            <div id="signUpBox">

                <h3>Sign up</h3>

                <label>username:
                    <input type="text" name="username" required></label><br>

                <label>password:
                    <input type="password" name="password" required></label><br>

                <label>email:
                    <input type="email" name="email" required></label><br>

                <label>Mobile Number (07 7777 777 77) 10 digits only:
                    <input type="number" name="mobileNo" required></label><br>

                <label>Address:
                    <input type="text" name="address" required></label><br>

                <label>Prove you're human...
                    <img src="images/antispam.gif">
                    <p>Please enter the text in the image</p>
                    <input type="text" name="anti-spam" required></label><br>
            </div>


            <input type="submit" name="sign-up" value="sign-up" class="btn btn-primary">

        </form>
    </div>
</div>

<?php require('template/footer.phtml') ?>
