<?php require('template/header.phtml') ?>


<div class="container">

    <h1><strong>Log in or sign up:</strong></h1>



        <form name="login" method="POST" action="login.php">

            <div id="loginBox">
                <h3>Login</h3>
                <label>username:
                    <input type="text" name="username" required></label><br>

                <label>password:
                    <input type="password" name="password" required></label><br>

                <input type="submit" name="login" value="Login" class="btn btn-primary">
            </div>

        </form>


        <form name="signUp" method="POST" action="login.php">

            <div id="signUpBox">

                <h3>Sign up</h3>

                <label>username:
                    <input type="text" name="username" required></label><br>

                <label>password:
                    <input type="password" name="password" required></label><br>

                <label>email:
                    <input type="text" name="email" required></label><br>


                <label>Address:
                    <input type="text" name="address" required></label><br>
            </div>

            <input type="submit" name="sign-up" value="sign-up" class="btn btn-primary">

        </form>

</div>

<?php require('template/footer.phtml') ?>
