<?php
//if(!(isset($_POST['login'])) && (isset($_SESSION['login_user']))){
 //   require ('template/header.phtml');
//} else {
    require ('template/header.phtml');
 //   echo 'try again';
//}
?>
<div class="container">
    <!--<div class="jumbotron">-->
    <div id="boxModel" class="col-xs-12">
        <h1 class="display-3">Come back soon!</h1>
        <p class="lead">We hope to see you again shortly</p>
        <hr class="my-2">
        <p>Cars.com, THE place to buy and sell a car</p>
<!--        <p class="lead">-->
<!--            <a class="btn btn-primary btn-lg" href="browse.php" role="button">Go browse</a>-->
<!--        </p>-->
        <!--    </div>-->
    </div>
</div>

<?php require('template/footer.phtml') ?>
