<?php require('template/header.phtml') ?>
    <body>

        <h3>Post an ad!</h3>
        <p><strong>Please provide, a title, description, and an image of your product</strong></p>
        <form name="postAd" method="post" action="../postAdvert.php">

            <div class="container">
                <div>
<!--                    <label>Make of Car<br>-->
<!--                        <input type="text" name="title" required></label><br/>-->

                    <label for="carDropMake">Make of Car</label>
                    <select name="title" id="carDropMake">
                        <option value="Mercedes"> Mercedes</option>
                        <option value="BMW"> BMW</option>
                        <option value="Tesla"> Tesla</option>
                        <option value="Ford"> Ford</option>
                        <option value="Audi"> Audi</option>
                        <option disabled>Super cars</option>
                        <option value="Lambo"> Lambo</option>
                    </select>
                    <br/>

                    <label>Price(£) <br/>
                        <input type="text" name="price" required></label><br/>

                    <label>Color<br/>
                        <input type="text" name="color" required></label><br/>

                    <label>Description<br/>
<!--                    <textarea rows="4" cols="50" required></textarea><br/>-->
                            <input type="text" name="description" required></label><br/>


<!--                        Need to do a check again the file size, and actual size.-->

<!--                        <form action="upload.php" method="post" enctype="multipart/form-data">-->
                            Select image to upload:
<!--                            <input type="text" name="photo_name" id="photo_name">-->
                            <input type="file" value="Upload Image" name="photo_name">
<!--                        </form>-->
                </div>

                <div>
                    <input type="submit" name="submit" value="submit" class="btn btn-primary">
                </div>

            </div>

        </form>

    </body>
<?php require('template/footer.phtml') ?>
