<?php require('template/header.phtml') ?>
<div class="container">
<!--    <div id="boxModel" class="col-sm-8 col-md-8">-->

            <div class="page-header">
                <h3>Wish List</h3>
            </div>

            <p>See your wish list here!</p>

        <input type="submit" name="wishlistDelete" value="Delete from wishlist" class="btn-danger"/>

        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">


            <!--        For each loop to loop through advert data so that the user can view advert information.-->


            <?php foreach ($view->wishlistDataSet as $wishlistData) {


// adverts.title ,adverts.photo_name, adverts.description, adverts.price , users.username, users.email, users.mobileNo


                echo
                    '<div class="col-xs-12 col-sm-6 col-lg-4">'.

                    '<div class = "card" >' .

                    '<div class = "card-body" >' .

                    '<h1 class="card-title"> User Id: ' . $wishlistData->getStudentID() . '</h1>' .

                    '<h1 class="card-title"> Name of Car: ' . $wishlistData->getTitle() . '</h1>' .

                    '<h2 class="card-title"> Price:</h2>' .

                    '<p class="card-text">£' . $wishlistData->getPrice() . '</p>' .

                    '<img src="../images/' . $wishlistData->getPhotoName() . ' "  class="img-thumbnail" id="images"  alt="No Image Available." />' . '<br/>' .

                    '<h2 class="card-title">Description: </h2>' .

                    '<p1 class="card-text"> ' . $wishlistData->getDescription() . '</p1>' . '<br/>' .

//                    '<h2 class="card-title">Color: </h2>' .

//                    '<p1 class="card-text">' . $advertData->getColor() . '<p1/>' . '<br/>' .

                    '<h2 class="card-title">User name: </h2>' .

                    '<p1 class="card-text"> ' . $wishlistData->getUsername() . '</p1>' . '<br/>' .

                    '<h2 class="card-title">Email: </h2>' .

                    '<p1 class="card-text"> ' . $wishlistData->getEmail() . '</p1>' . '<br/>' .

                    '<h2 class="card-title">Mobile number: </h2>' .

                    '<p1 class="card-text"> ' . $wishlistData->getMobileNo() . '</p1>' . '<br/>' .

                    '<a href="wishlist.php?wishlistDelete=' . $wishlistData->getWishlistId() . '" type="button" class="btn btn-primary">Remove</a>'




                    . '</div>'
                    . '</div>'
                    . '</div>'
                    . '<br/>'
                    . '<br/>';
            }
            ?>






<?php require('template/footer.phtml') ?>
