    </div>


    <div class=row">
        <div class="container">
            <div id="footer" class="col-xs-12 col-lg-12">
                <h2> Cars.com </h2>
                <p>THE place to buy & sell a car!</p>
                <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
                <script src="../../js/pageActions.js"></script>
            </div>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>

</body>
</html>